---
- name: "{{ unit_name }} systemd service file"
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ unit_name }}.service
  notify: restart {{ unit_name }}

- name: "{{ unit_name }} systemd service"
  systemd:
    name: "{{ unit_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
