---
- name: "{{ name }} systemd service file"
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ name }}.service
  notify: restart {{ name }}

- name: "{{ name }} systemd service"
  systemd:
    name: "{{ name }}"
    state: started
    enabled: yes
    daemon_reload: yes
