---
nas:
  uid: 2000
  gid: 100

app_basedir: /data/app
media_dir: /data/media
downloads_dir: "{{ media_dir }}/downloads"
influxdb_dir: /var/lib/influxdb
grafana_dir: /var/lib/grafana

backup_calendar: daily
backup_docs:
  source_dir: /data/documents
  repository: /data/backup
  envfile: /etc/borg.env
  create_options: []
  prune_options:
  - --keep-daily=7
  - --keep-weekly=4
  rclone:
    config: /data/.rclone-backup.conf
    target: b2:vizcaino-bour-backup
    options:
    - -v
    - --transfers 8


backup_media:
  options:
  - --config /data/.rclone.conf
  - --exclude downloads/
  - --stats 0
  - --verbose
  source_dir: /data/.media/local
  target_url: acd-encrypted:/

services:
  couchpotato:
    description: CouchPotato
    rkt:
      image:
        name: docker://linuxserver/couchpotato
        tag: latest

      options:
      - --net=host
      - --dns=host
      - --set-env PUID={{ nas.uid }}
      - --set-env PGID={{ nas.gid }}
      - --set-env TZ=Europe/Paris

      volumes:
      - name: config
        source: "{{ app_basedir }}/couchpotato"
        target: /config
      - name: media
        source: "{{ media_dir }}"
        target: /media

  nzbget:
    description: NZBget - Usenet Grabber
    rkt:
      image:
        name: docker://linuxserver/nzbget
        tag: latest

      options:
      - --net=host
      - --dns=host
      - --set-env PUID={{ nas.uid }}
      - --set-env PGID={{ nas.gid }}
      - --set-env TZ=Europe/Paris

      volumes:
      - name: config
        source: "{{ app_basedir }}/nzbget"
        target: /config
      - name: downloads
        source: "{{ downloads_dir }}"
        target: /downloads

  sonarr:
    description: Sonarr - TV Shows
    rkt:
      image:
        name: docker://linuxserver/sonarr
        tag: latest

      options:
      - --net=host
      - --dns=host
      - --set-env PUID={{ nas.uid }}
      - --set-env PGID={{ nas.gid }}

      volumes:
      - name: rtc
        source: /dev/rtc
        target: /dev/rtc
      - name: config
        source: "{{ app_basedir }}/sonarr"
        target: /config
      - name: media
        source: "{{ media_dir }}"
        target: /media

  deluge:
    description: Deluge Bittorrent client
    rkt:
      image:
        name: docker://linuxserver/deluge
        tag: latest

      options:
      - --net=host
      - --dns=host
      - --set-env PUID={{ nas.uid }}
      - --set-env PGID={{ nas.gid }}

      volumes:
      - name: config
        source: "{{ app_basedir }}/deluge"
        target: /config
      - name: media
        source: "{{ media_dir }}"
        target: /media

  influxdb:
    description: InfluxDB timeseries database
    rkt:
      image:
        name: docker://influxdb
        tag: 1.2.0-alpine

      options:
      - --net=host
      - --dns=host

      volumes:
      - name: data
        source: "{{ influxdb_dir }}"
        target: /var/lib/influxdb

  grafana:
    description: Grafana
    rkt:
      image:
        name: docker://grafana/grafana
        tag: 4.1.1

      options:
      - --net=host
      - --dns=host
      - --set-env GF_AUTH_ANONYMOUS_ENABLED=true

      volumes:
      - name: data
        source: "{{ grafana_dir }}"
        target: /var/lib/grafana
